apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newgoappofapps-prod
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/newgoappofapps/overlays/prod
    repoURL: https://github.com/stephanie-cy/newgoappofapps-gitops
    targetRevision: main
  destination:
    namespace: target-ns-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
