apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: newgoappofapps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: newgoappofapps 
  name: newgoappofapps
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: newgoappofapps 
